package Part_1;

public class P1_E5 {
    public static void main(String[] args) {
        boolean p, q;
            System.out.println("P\t\tQ\t\tAND\t\tOR\t\tXOR\t\tNOT");
p = true ; q = true;
        if (p==true) System.out.print(1);
                else System.out.print(0);
                                         System.out.print("\t\t");
        if (q==true) System.out.print(1);
                else System.out.print(0);
                                         System.out.print("\t\t");
        if ((p&q)==true) System.out.print(1);
                else System.out.print(0);
                                        System.out.print("\t\t");
        if ((p|q)==true) System.out.print(1);
                 else System.out.print(0);
                                        System.out.print("\t\t");
        if ((p^q)==true) System.out.print(1);
                 else System.out.print(0);
                                        System.out.print("\t\t");
        if ((!p)==true) System.out.print(1);
                 else System.out.print(0);
                                        System.out.println("\t\t");
p = true; q = false;
        if (p==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if (q==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p&q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p|q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p^q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((!p)==true) System.out.print(1);
        else System.out.print(0);
        System.out.println("\t\t");
p = false; q = true;
        if (p==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if (q==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p&q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p|q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p^q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((!p)==true) System.out.print(1);
        else System.out.print(0);
        System.out.println("\t\t");
p = false; q = false;
        if (p==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if (q==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p&q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p|q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((p^q)==true) System.out.print(1);
        else System.out.print(0);
        System.out.print("\t\t");
        if ((!p)==true) System.out.print(1);
        else System.out.print(0);
        System.out.println("\t\t");
    }
}
